#!/bin/bash

# Script to precompile Metal shaders for iOS
# This creates a binary .metallib file that can be loaded at runtime

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_DIR="$(dirname "$SCRIPT_DIR")"
AUTOGEN_DIR="$IOS_DIR/autogenerated"
CLASSES_DIR="$IOS_DIR/Classes"
METAL_SOURCE="$AUTOGEN_DIR/ggml-metal-embed.metal"
OUTPUT_DIR="$IOS_DIR/Resources"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

echo "Compiling Metal shaders for iOS..."
echo "  Source: $METAL_SOURCE"
echo "  Output: $OUTPUT_DIR/default.metallib"

# Check if source exists
if [ ! -f "$METAL_SOURCE" ]; then
    echo "Error: Metal source not found at $METAL_SOURCE"
    echo "Run the following command first:"
    echo "  cd $IOS_DIR"
    echo "  ./scripts/generate_metal_embed.sh"
    exit 1
fi

# Compile for iOS (ARM64)
# Step 1: Compile .metal to .air (Apple Intermediate Representation)
xcrun -sdk iphoneos metal \
    -std=ios-metal2.3 \
    -O3 \
    -I"$CLASSES_DIR/whisper/ggml/include" \
    -I"$CLASSES_DIR/whisper/ggml/src" \
    -I"$CLASSES_DIR/whisper/ggml/src/ggml-metal" \
    -c "$METAL_SOURCE" \
    -o "$OUTPUT_DIR/ggml-metal.air"

if [ $? -ne 0 ]; then
    echo "Error: Failed to compile Metal shaders to AIR"
    exit 1
fi

# Step 2: Create metallib from .air
xcrun -sdk iphoneos metallib \
    "$OUTPUT_DIR/ggml-metal.air" \
    -o "$OUTPUT_DIR/default.metallib"

if [ $? -ne 0 ]; then
    echo "Error: Failed to create metallib"
    rm -f "$OUTPUT_DIR/ggml-metal.air"
    exit 1
fi

# Clean up intermediate file
rm -f "$OUTPUT_DIR/ggml-metal.air"

echo "✓ Successfully built Metal library at $OUTPUT_DIR/default.metallib"
ls -lh "$OUTPUT_DIR/default.metallib"
