#!/bin/bash

# Script to generate the embedded Metal source file
# This merges ggml-common.h and ggml-metal-impl.h into ggml-metal.metal

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_DIR="$(dirname "$SCRIPT_DIR")"
AUTOGEN_DIR="$IOS_DIR/autogenerated"
CLASSES_DIR="$IOS_DIR/Classes"

METAL_SOURCE="$CLASSES_DIR/whisper/ggml/src/ggml-metal/ggml-metal.metal"
METAL_IMPL="$CLASSES_DIR/whisper/ggml/src/ggml-metal/ggml-metal-impl.h"
GGML_COMMON="$CLASSES_DIR/whisper/ggml/include/ggml-common.h"

METAL_EMBED_TMP="$AUTOGEN_DIR/ggml-metal-embed.metal.tmp"
METAL_EMBED="$AUTOGEN_DIR/ggml-metal-embed.metal"

# Create autogenerated directory if it doesn't exist
mkdir -p "$AUTOGEN_DIR"

echo "Generating embedded Metal source..."
echo "  Metal source: $METAL_SOURCE"
echo "  Common header: $GGML_COMMON"
echo "  Implementation header: $METAL_IMPL"
echo "  Output: $METAL_EMBED"

# Step 1: Embed ggml-common.h
sed -e "/__embed_ggml-common.h__/r $GGML_COMMON" \
    -e "/__embed_ggml-common.h__/d" \
    < "$METAL_SOURCE" > "$METAL_EMBED_TMP"

# Step 2: Embed ggml-metal-impl.h
sed -e "/#include \"ggml-metal-impl.h\"/r $METAL_IMPL" \
    -e "/#include \"ggml-metal-impl.h\"/d" \
    < "$METAL_EMBED_TMP" > "$METAL_EMBED"

# Clean up temporary file
rm -f "$METAL_EMBED_TMP"

echo "✓ Successfully generated embedded Metal source"
wc -l "$METAL_EMBED"
